[package]
name = "SafeSignalBlockchainRegistry"
version = "0.1.0"
edition = "2021"
# cairo = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
